// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwJntj9TG6MJsIu4xBLlscnI2XOq2L1FQ',
    appId: '1:516046146283:ios:311549442a7264b6a38cae',
    messagingSenderId: '516046146283',
    projectId: 'ecommerce-3ee17',
    storageBucket: 'ecommerce-3ee17.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwJntj9TG6MJsIu4xBLlscnI2XOq2L1FQ',
    appId: '1:516046146283:ios:311549442a7264b6a38cae',
    messagingSenderId: '516046146283',
    projectId: 'ecommerce-3ee17',
    storageBucket: 'ecommerce-3ee17.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjqgnOIoVQNvCUfSXXoOK0wCNsYqUV44I',
    appId: '1:516046146283:web:6ddc7d8b3fcc3726a38cae',
    messagingSenderId: '516046146283',
    projectId: 'ecommerce-3ee17',
    authDomain: 'ecommerce-3ee17.firebaseapp.com',
    storageBucket: 'ecommerce-3ee17.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGxtAjXxNQ7sRTJdlVZN_PW70o-aLkkBg',
    appId: '1:516046146283:android:fc9999d40eeb73c4a38cae',
    messagingSenderId: '516046146283',
    projectId: 'ecommerce-3ee17',
    storageBucket: 'ecommerce-3ee17.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjqgnOIoVQNvCUfSXXoOK0wCNsYqUV44I',
    appId: '1:516046146283:web:8c897b9373ff6028a38cae',
    messagingSenderId: '516046146283',
    projectId: 'ecommerce-3ee17',
    authDomain: 'ecommerce-3ee17.firebaseapp.com',
    storageBucket: 'ecommerce-3ee17.appspot.com',
  );

}